### ISSUE TITLE
Mosquitto cannot start up properly

### ISSUE THREAD

**Issue by jaceks2106** [OS2iot/OS2IoT-docker#2]
Hello,

I have a problem with running whole infrastructure on localhost using Docker. After successful fetch and installation of all services, I noticed, that backend _os2iot-docker_os2iot-backend (port: 3000)_ cannot run properly - the last error terminates the whole app: 

``` bash
[Nest] 19 - 06/17/2021, 11:01:13 AM [GenericChirpstackConfigurationService] GET http://chirpstack-application-server:8080/api/network-servers?limit=100&offset=0 got error: Error: connect ECONNREFUSED 172.20.0.12:8080 +17ms
```

Then I started investigating what's happening in service _os2iot-docker_chirpstack-application-server (port: 8080)_

``` bash
time="2021-06-17T11:27:21Z" level=error msg="integration/mqtt: connecting to broker error, will retry in 2s: Network Error : dial tcp 172.20.0.7:1883: connect: connection refused"
time="2021-06-17T11:27:23Z" level=error msg="integration/mqtt: connecting to broker error, will retry in 2s: Network Error : dial tcp 172.20.0.7:1883: connect: connection refused"
time="2021-06-17T11:27:25Z" level=error msg="integration/mqtt: connecting to broker error, will retry in 2s: Network Error : dial tcp 172.20.0.7:1883: connect: connection refused"
(...) and so on
```

Port points me to Mosquitto _os2iot-docker_mosquitto (port 1883)_:

``` bash
1623927668: mosquitto version 2.0.11 starting
1623927668: Config loaded from /mosquitto/config/mosquitto.conf.
1623927668: Starting in local only mode. Connections will only be possible from clients running on this machine.
1623927668: Create a configuration file which defines a listener to allow remote access.
1623927668: For more details see https://mosquitto.org/documentation/authentication-methods/
1623927668: Opening ipv4 listen socket on port 1883.
1623927668: Opening ipv6 listen socket on port 1883.
1623927668: Error: Address not available
1623927668: mosquitto version 2.0.11 running
```

I found similar issue at this link https://github.com/eclipse/mosquitto/issues/2040 and they say that line `listener 1883` should be added to Mosquitto configuration file, but there is no such file in this solution.

Reproduction steps:
1. Download all 3 repos
2. Go into docker repo and run `docker compose up`

**Comment by Joiversen** [comment]
Hi @jaceks2106,

Thank you very much for letting us know - by doing so you help improve OS2iot.

We will asap make a quick fix thats locks the version of Mosquitto to v.1.6. 

When we are ready, we will then make the needed changes to update to version 2.0

**Comment by Joiversen** [comment]
Is it working in your end as well now? @jaceks2106

**Comment by jaceks2106** [comment]
I have tested it @Joiversen on hotfix branch from this PR and it works :). Thanks for the quick response :)
